CREATE TABLE CATEGORY(
category_id INTEGER PRIMARY KEY AUTO_INCREMENT,
category_name VARCHAR(20)
);


CREATE TABLE UNIVERSITY(
university_id INTEGER PRIMARY KEY AUTO_INCREMENT,
university_name VARCHAR(60)
);

CREATE TABLE FIELD(
field_id INTEGER PRIMARY KEY AUTO_INCREMENT,
field_name VARCHAR(30)
);

CREATE TABLE RESEARCHER(
researcher_id INTEGER PRIMARY KEY AUTO_INCREMENT,
first_name VARCHAR(20),
last_name VARCHAR(20),
email VARCHAR(40) UNIQUE,
password VARCHAR(64),
field_id INTEGER,
university_id INTEGER,
CONSTRAINT field_fk FOREIGN KEY(field_id) REFERENCES FIELD(field_id) ON DELETE SET NULL,
CONSTRAINT uni_fk FOREIGN KEY(university_id) REFERENCES UNIVERSITY(university_id) ON DELETE SET NULL
);


CREATE TABLE KEYWORD(
keyword_id INTEGER PRIMARY KEY AUTO_INCREMENT,
keyword_name VARCHAR(20)
);


CREATE TABLE POST(
post_id INTEGER PRIMARY KEY AUTO_INCREMENT,
title VARCHAR(50),
description VARCHAR(250),
content TEXT,
researcher_id INTEGER,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
CONSTRAINT res_fk FOREIGN KEY(researcher_id) REFERENCES RESEARCHER(researcher_id) ON DELETE CASCADE
);


CREATE TABLE POST_KEYWORDS(
post_keyword_id INTEGER PRIMARY KEY AUTO_INCREMENT,
post_id INTEGER,
keyword_id INTEGER,
CONSTRAINT post_fk FOREIGN KEY(post_id) REFERENCES POST(post_id) ON DELETE CASCADE,
CONSTRAINT keyword_fk FOREIGN KEY(keyword_id) REFERENCES KEYWORD(keyword_id) ON DELETE CASCADE
);

CREATE TABLE POST_CATEGORY(
post_category_id INTEGER PRIMARY KEY AUTO_INCREMENT,
post_id INTEGER,
category_id INTEGER,
CONSTRAINT fk_post FOREIGN KEY(post_id) REFERENCES POST(post_id) ON DELETE CASCADE,
CONSTRAINT category_fk FOREIGN KEY(category_id) REFERENCES CATEGORY(category_id) ON DELETE CASCADE
);


CREATE TABLE POST_LIKE(
like_id INTEGER PRIMARY KEY AUTO_INCREMENT,
researcher_id INTEGER,
post_id INTEGER,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
CONSTRAINT fk_p FOREIGN KEY(post_id) REFERENCES POST(post_id) ON DELETE CASCADE,
CONSTRAINT r_fk FOREIGN KEY(researcher_id) REFERENCES RESEARCHER(researcher_id) ON DELETE CASCADE,
CONSTRAINT unique_like UNIQUE (researcher_id, post_id)
);

CREATE TABLE COMMENT(
comment_id INTEGER PRIMARY KEY AUTO_INCREMENT,
content TEXT,
researcher_id INTEGER,
post_id INTEGER,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
CONSTRAINT p_fk FOREIGN KEY(post_id) REFERENCES POST(post_id) ON DELETE CASCADE,
CONSTRAINT fk_r FOREIGN KEY(researcher_id) REFERENCES RESEARCHER(researcher_id) ON DELETE CASCADE
);



























